### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Levminer** [Levminer/authme#108]
Support multiple languages

- [x] Application
- [x] Menu and tray
- [x] Dialogs
- [x] Buttons
- [x] Texts

**Comment by nothing-fr** [comment]
Hello,
I'm interested in this feature, what is the process to translate the application into another language? I don't see any language files in the application.

**Comment by Levminer** [comment]
> Hello, I'm interested in this feature, what is the process to translate the application into another language? I don't see any language files in the application.

Hi, Authme 3 was translatable. Authme 4 was a complete rewrite and the localisation feature was not reimplemented (because no one used it).

**Comment by nothing-fr** [comment]
Our users have trouble with English, so without this feature, it won't be possible to use it...
It's a pity, because the application is simple and efficient...

**Comment by gismomtl** [comment]
Hi, I vote also to reintroduce this feature and if anything can be done to help you restoring this feature, let me know..

**Comment by gismomtl** [comment]
Ok let us know what we can do
