### ISSUE TITLE
Change password

### ISSUE THREAD

**Issue by Levminer** [Levminer/authme#183]
- Ability to change password

**Comment by Royer-16** [comment]
> * Posibilidad de cambiar la contraseña

https://github.com/Levminer/authme/issues/183#issue-1125321212

**Comment by Levminer** [comment]
> > * Posibilidad de cambiar la contraseña
> 
> https://github.com/Levminer/authme/issues/183#issue-1125321212

English please! Google Translate was useless.

**Comment by Levminer** [comment]
Not going to be implemented.
