### ISSUE TITLE
Support for Flatpak and .deb file on Linux

### ISSUE THREAD

**Issue by dtantono** [Levminer/authme#233]
### Before the feature request.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a feature request that matches the one I want to file, without success.

### Your feature request related to the problem

Hi
I know there is snap/Appimage version. But, I hope there will be Flatpak/.deb version for cover many distros. what do you think?

### Describe the solution you'd like or alternatives you've considered

snap and appimage is fine. But, not everyone like that format.

**Comment by Levminer** [comment]
.deb is now available

**Comment by dtantono** [comment]
@Levminer where?
![image](https://user-images.githubusercontent.com/29157187/199202449-aad1065b-0967-4880-90d4-c3540ff44e98.png)

**Comment by Levminer** [comment]
> @Levminer where? ![image](https://user-images.githubusercontent.com/29157187/199202449-aad1065b-0967-4880-90d4-c3540ff44e98.png)

It's currently in beta: https://github.com/Levminer/authme/releases/tag/4.0.0-beta.2

But check out the [migration](https://github.com/Levminer/authme/tree/4.0.0-beta.2#migration) from 3.0.0 if you are already using Authme.
