### ISSUE TITLE
 Hardware Barcode scanner

### ISSUE THREAD

**Issue by NonStop37** [Levminer/authme#236]
### Before the feature request.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a feature request that matches the one I want to file, without success.

### Your feature request related to the problem

Здравствуйте! Можете добавить аппаратный сканер qr кода. Удивился что обычное считывание сканером штрихода не работает. Спасибо

### Describe the solution you'd like or alternatives you've considered

realization

### Additional information

if you need a tester for wired or wireless (any) barcode scanners, I'm ready!

**Comment by NonStop37** [comment]
![image](https://user-images.githubusercontent.com/115445580/194803063-d2c39693-bb42-48f2-a0e6-f91e1f877c50.png)

**Comment by Levminer** [comment]
Hi! I'm curious what's your use case for using a barcode scanner?
