### ISSUE TITLE
https://docs.authme.levminer.com/ Down?

### ISSUE THREAD

**Issue by Andrew-McCall** [Levminer/authme#241]
### Before the bug report.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a bug that matches the one I want to file, without success.

### Authme/System information

AuthMe 4.0.0

### Describe the bug

https://docs.authme.levminer.com/ is not live despite the redirect from in-app.

### To reproduce

Crtl-D or Help -> Document -> Redirect.
Open's my browser to 

```
This site can’t be reachedCheck if there is a typo in docs.authme.levminer.com.
If spelling is correct, [try running windows network Diagnostics](javascript:diagnoseErrors()).
DNS_PROBE_FINISHED_NXDOMAIN
```

**Comment by Levminer** [comment]
Are you sure you are using Authme 4.0.0? 
The docs site is removed because Authme 4.0.0 includes all docs in the app.

**Comment by Andrew-McCall** [comment]
Appologies. 

It's Version 3.3.1 - The latest version from the Microsoft Store.
