### ISSUE TITLE
Crash Issue

### ISSUE THREAD

**Issue by BD-Domii** [Levminer/authme#243]
### Before the bug report.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a bug that matches the one I want to file, without success.

### Authme/System information

![Screenshot_20221129_060738](https://user-images.githubusercontent.com/119460939/204669428-3cc58217-2c10-4db6-8aa9-8dd3bc866f05.png)

![image](https://user-images.githubusercontent.com/119460939/204670364-9ba5b2d4-c8d5-4c32-b236-17e248a0c013.png)

I have my school account, connected with Authme as my 2FA, since I don't have a phone number.  I need to access my onedrive in the account, and can't because I can't verify it, since I can't run Authme atm. Is there a solution to this problem? Everytime I try to run the app it shows the message shown above. 

Best regards, 
Domii

### Describe the bug

Instant crash. It will not run.  
When I boot the pc all over, it shows the same message as pop-up since, it's in the startup programs for me.

### To reproduce

I just try to run it. It would usually boot when I needed it, all I had to do it double-click on the application, or run it through the menu tab. It has done this for the past few days. I honestly don't know where things went wrong.

**Comment by BD-Domii** [comment]
I initially downloaded Authme from the Microsoft Store by reading, a few things in here, I realized it was an outdated version, and so I downloaded a more recent version from their official webpage. It resolved my problem, I am sorry for even making a ticket.

**Comment by Levminer** [comment]
No problem. I will update the store version when Microsoft finally approves it.
