### ISSUE TITLE
Bug when we use the function for close the app when we click on the cross

### ISSUE THREAD

**Issue by Skryzie** [Levminer/authme#248]
### Before the bug report.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a bug that matches the one I want to file, without success.

### Authme/System information

3.3.1 
Windows 11

### Authme log

![Capture d’écran 2023-01-21 120550](https://user-images.githubusercontent.com/38785300/213864215-43c8b318-afad-458a-94d1-53aa9c728bc9.png)

### Describe the bug

When we close the app with cross, with the function "Close app to tray" disable. The icon stay on the system tray and when we double click on, this error appear
![Capture d’écran 2023-01-21 120550](https://user-images.githubusercontent.com/38785300/213864266-f80ff632-b4c2-46c9-b897-022dca92e85b.png)

### To reproduce

Disabled in the settings "close app to tray"
Close the app with the cross
Click on Authme icon in the system tray

**Comment by Levminer** [comment]
Hi!

Thanks for the report!

Authme 3 is not supported any more. Please [migrate](https://github.com/Levminer/authme/#migration) to [Authme 4](https://github.com/Levminer/authme/releases/tag/4.0.2).

**Comment by Skryzie** [comment]
Authme 4 update is not available  in Windows Store ?

**Comment by Levminer** [comment]
> Authme 4 update is not available in Windows Store ?

Currently not.

**Comment by Skryzie** [comment]
I have another problem now. When i try to import a picture of 2FA exportation of Google Authenticator. That do nothing :(

**Comment by Skryzie** [comment]
And i have this error when i use webcam 
![Capture d’écran 2023-01-22 130053](https://user-images.githubusercontent.com/38785300/213914677-321ea99f-123e-42ed-ba5e-c5e033b77628.png)

**Comment by Levminer** [comment]
@Skryzie Did you figure out the webcam problem?

**Comment by Skryzie** [comment]
No sorry, the bug is still here.

When i try to scan the export QR Code from Google Authentificator, this error appear.

![Capture d’écran 2023-01-22 192521](https://user-images.githubusercontent.com/38785300/213933246-ccaef49d-2722-454d-9fa8-1b757ab01ea8.png)

This bug is not present on Authme 3

**Comment by Levminer** [comment]
> No sorry, the bug is still here.
> 
> When i try to scan the export QR Code from Google Authentificator, this error appear.
> 
> ![Capture d’écran 2023-01-22 192521](https://user-images.githubusercontent.com/38785300/213933246-ccaef49d-2722-454d-9fa8-1b757ab01ea8.png)
> 
> This bug is not present on Authme 3

Can you send a debug log? Inside Authme: Settings > Scroll down to About -> Show logs -> Copy and paste the contents here

**Comment by Skryzie** [comment]
[AUTHME LOG] (2023. 01. 22. 19:22:05) Authme 4.0.2 release.230110.145902
[AUTHME LOG] (2023. 01. 22. 19:22:05) Path changed: /
[AUTHME LOG] (2023. 01. 22. 19:22:26) Path changed: /codes
[AUTHME LOG] (2023. 01. 22. 19:24:20) Path changed: /settings
[AUTHME LOG] (2023. 01. 22. 19:24:34) Path changed: /codes
[AUTHME LOG] (2023. 01. 22. 19:24:36) Path changed: /import
[AUTHME ERROR] (2023. 01. 22. 19:25:00) Error during webcam import: EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'sha256-MGkNehxdvHoxgLlUEyzLHgXmr9XjrOmJGC9xhv+JRxY=' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='".

**Comment by Levminer** [comment]
Closing this in favour of #250

**Comment by Skryzie** [comment]
Thank, that's work well now 🙂
