### ISSUE TITLE
Submit to Apple App Store

### ISSUE THREAD

**Issue by rakleed** [Levminer/authme#249]
### Before the feature request.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a feature request that matches the one I want to file, without success.

### Your feature request related to the problem

On macOS, the ability to download the app from the App Store is lacking, as there is auto-update, moderation from Apple, and user reviews.

### Describe the solution you'd like or alternatives you've considered

Submit Authme to Apple App Store.

**Comment by Levminer** [comment]
Hi!

Submitting to the apple app store requires a developer account (100$) and a mac to test/build the app. I have neither currently, so not going to happen any time soon.

**Comment by Levminer** [comment]
This is blocked by: https://github.com/tauri-apps/tauri/issues/3716

Also I don't want to deal with Apple's strict app store policies, but the macos binary will be signed soon.
