### ISSUE TITLE
Scanning QR codes results in error

### ISSUE THREAD

**Issue by schweppes-0x** [Levminer/authme#250]
### Before the bug report.

- [x] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a bug that matches the one I want to file, without success.

### Authme/System information

Authme 4.0.2 on Windows 11
Google Authenticator on iPhone 13Pro

### Describe the bug

Error message:
![image](https://user-images.githubusercontent.com/88944709/221811253-f966dca5-6401-4f08-9374-ed70f1bd7e5d.png)

### To reproduce

1.  In Authme app : Import > More options > Webcam > use Webcam
2. Within Google Authenticator app : Export accounts > Continue > Export
3. Scan the QR

**Comment by Levminer** [comment]
Hi!

Thanks for reporting this, I will look into this.

**Comment by Levminer** [comment]
@schweppes-0x should be fixed now, you can test it if you want: https://api.levminer.com/api/v1/authme/alpha/windows
