### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Levminer** [Levminer/authme#258]
Authme 3 had localization, but it was not reimplemented. Authme 3 had around ~300 lines to translate, if enough people volunteer to translate I reimplement the feature.

**Comment by gismomtl** [comment]
Yes I can help you with that

**Comment by Levminer** [comment]
Hi everyone!

Started working on this, it's almost done.
I will update this issue if I'm done with everything and made some instructions on how to translate.

**Comment by Levminer** [comment]
The translation is mostly done.

If you want to translate Authme:

1. Go to interface/utils/language
2. Make a copy of en.ts 
3. Rename the file for the language that you want to translate (de.ts, fr.ts, es.ts)
4. Translate the strings
5. Make a PR
