### ISSUE TITLE
Import from Aegis Authenticator

### ISSUE THREAD

**Issue by rkt3ch** [Levminer/authme#264]
### Before the feature request.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a feature request that matches the one I want to file, without success.

### Your feature request related to the problem

Hi, thank you for your time and effort. Im trying to import file from Aegis & andOTP Authenticator to Authme but help section is not working. 

Thank you 

### Describe the solution you'd like or alternatives you've considered

Hi, thank you for your time and effort. Im trying to import file from Aegis & andOTP Authenticator to Authme but help section is not working. 

Thank you

**Comment by Levminer** [comment]
Related: https://github.com/Levminer/authme/issues/100
