### ISSUE TITLE
Localization PR

### ISSUE THREAD

**Issue by gismomtl** [Levminer/authme#265]
Hi,
following https://github.com/Levminer/authme/issues/258, 
can you share/point to the the code that was published in a previous version that contained the localized module, I will use it to create a new PR with updated data

**Comment by Levminer** [comment]
Hi,
thanks for the help, this was the old implementation, but a lot of strings changed, so it has to be done from the start.
https://github.com/Levminer/authme/blob/4233997d88ce3e5aaf6190def842b95e793253c0/languages/en.js

**Comment by Levminer** [comment]
Hi @gismomtl, did you make any progress? I finally have some time to work on this, if you haven't started it.

**Comment by gismomtl** [comment]
Hi @Levminer , I didnt yet complete the change, I'm only at the beginning. You can work on it and I can help you if you want to dispatch tasks
