### ISSUE TITLE
Ubuntu Snpacraft update

### ISSUE THREAD

**Issue by Goldinium** [Levminer/authme#271]
### Before the feature request.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a feature request that matches the one I want to file, without success.

### Your feature request related to the problem

Great job Levminer! the app is outstanding

However I noticed the app version in Ubuntu snapcraft is still 3
Please update it to the 4th version..

### Describe the solution you'd like or alternatives you've considered

Thank you

**Comment by Levminer** [comment]
Hi! Tauri currenty doesn't support snap. More info: https://github.com/tauri-apps/tauri/issues/4402
