### ISSUE TITLE
Auto-focus for the password field

### ISSUE THREAD

**Issue by ssrmm** [Levminer/authme#273]
### Before the feature request.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a feature request that matches the one I want to file, without success.

### Your feature request related to the problem

When starting the application it would be nice if the password field was focused automatically, similar to how the search-field already has focus automatically when the codes are displayed. That way you can immediately start typing the password and don't need to click the password field first.

### Describe the solution you'd like or alternatives you've considered

See above

**Comment by Levminer** [comment]
Will be fixed in the next version, thanks!
