### ISSUE TITLE
Issue with snap package

### ISSUE THREAD

**Issue by OliverZolSza** [Levminer/authme#274]
### Before the bug report.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a bug that matches the one I want to file, without success.

### Authme/System information

Authme: 3.3.2 

Electron: 19.0.8
Chrome: 102.0.5005.148 

OS version: Linux x64 6.2.0-37-generic
Hardware info: AMD Ryzen 3 4300U with Radeon Graphics 8GB RAM 

Release date: 2022. July 12.
Build number: release.220712.114056 

Created by: Lőrik Levente

### Describe the bug

I keep getting this error when opening the app 
![Screenshot from 2023-12-02 17-15-37](https://github.com/Levminer/authme/assets/150553059/9d38ece2-fd4b-4d31-a477-29880a7cf4ea)

### To reproduce

Open the app in Ubuntu 22.04

**Comment by Levminer** [comment]
Hi! Tauri currenty doesn't support snap. More info: https://github.com/tauri-apps/tauri/issues/4402
