### ISSUE TITLE
Error in logs when Optional analytics enabled

### ISSUE THREAD

**Issue by bsd-source** [Levminer/authme#276]
### Before the bug report.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a bug that matches the one I want to file, without success.

### Authme/System information

Authme: 4.2.1 

Tauri: 1.5.3
WebKit: 17.0

OS version: Manjaro Linux x64 23.1.1
Hardware info: 12th Gen Intel Core i3-1215U 11 GB RAM

Release date: 2023. December 12.
Build number: release.231212.090943

Created by: Lőrik Levente

### Authme log

[AUTHME LOG] (2024. 01. 06. 5:34:39) Authme 4.2.1 release.231212.090943
[AUTHME LOG] (2024. 01. 06. 5:34:39) Path changed: /
[AUTHME LOG] (2024. 01. 06. 5:34:39) Path changed: /codes
[AUTHME ERROR] (2024. 01. 06. 5:34:39) Unknown runtime error occurred: TypeError: (await un("system_info")).split is not a function. (In '(await un("system_info")).split("+")', '(await un("system_info")).split' is undefined)
[AUTHME ERROR] (2024. 01. 06. 5:34:39) Failed to check for update: the platform `linux-x86_64` was not found on the response `platforms` object

### Describe the bug

Error in logs with analytics enabled in app during startup. I haven't used the app long enough to know if the error shows up in the logs file after using the app for an extended period of time.

I guess the update error that shows in the logs as well is a possible separate bug.

### To reproduce

Make sure analytics is enabled before starting authme. Check the logs for the error. There wasn't a visual popup error, it only shows up in the logs.

### Additional information

The error appeared when using both the appimage as well as the deb binary.

**Comment by Levminer** [comment]
Thanks for the report!

The system_info function was changed on the Rust side and I forgot to change it on the JS side. Will be fixed in the next update.

The updater doesn't work in Linux currently.
