### ISSUE TITLE
Import from Authy

### ISSUE THREAD

**Issue by Newcool1230** [Levminer/authme#279]
### Before the feature request.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a feature request that matches the one I want to file, without success.

### Your feature request related to the problem

[Authy for Desktop End of Life (EOL) ](https://support.authy.com/hc/en-us/articles/17592416719003-Authy-for-Desktop-End-of-Life-EOL-). Authy has announced EOL for their desktop 2fa application. I'm looking for a way to import authy TOTP keys to authme.

### Describe the solution you'd like or alternatives you've considered

A button to take data from the Authy app and import it to authme.

**Comment by Levminer** [comment]
As stated by Authy in the post, there is no way to export codes. You should log in to every account you use, disable 2FA, re-enable it and import the secret(s) using the manual import in Authme.

**Comment by Newcool1230** [comment]
> As stated by Authy in the post, there is no way to export codes. You should log in to every account you use, disable 2FA, re-enable it and import the secret(s) using the manual import in Authme.

Ah ok, I saw that [Aegis](https://github.com/beemdevelopment/Aegis#features) was able to import from Authy android but only from rooted phones (I don't have any atm). Thought there was a way to import from Authy Desktop.

**Comment by Ryuo1** [comment]
If you have a computer: https://gist.github.com/gboudreau/94bb0c11a6209c82418d01a59d958c93

If you want to use your phone. install this GO package in termux: https://github.com/jmhobbs/authy-cli
