### ISSUE TITLE
Font size is too large with 150% on win11

### ISSUE THREAD

**Issue by mslxl** [Levminer/authme#280]
### Before the bug report.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a bug that matches the one I want to file, without success.

### Authme/System information

Authme: 4.2.1
Windows11: 23H2
Screen display resolution: 2560x 1600
Display scale: 150%

### Describe the bug

Font is extraordinary large on all page, which caused others see my screen clearly. Also it's hard to explore my codes because the number of items display is very small.

Pictures took by phone:
![IMG20240112143604](https://github.com/Levminer/authme/assets/11132880/0b05976c-4f87-488b-8169-5e7991185722)
![IMG20240112143529](https://github.com/Levminer/authme/assets/11132880/839a1d6a-5542-47c0-ba32-a4ea5b767fa8)

But when I set display scale to 100%, all font display normally.

### To reproduce

Just start Authme on Windows with display scale simply

**Comment by Levminer** [comment]
Thanks for the report!

The font size is 14px now instead of 16px when using 125% scale. Its not the greatest solution but, going lower than 14px breaks the UI.

If you are concerned that your codes are being shown turn on blur codes in the settings.

**Comment by Crayder** [comment]
Can this be re-opened? It's not really resolved. There needs to be a solution lol. Let users set their own zoom factor maybe?

As you can see here, the font is HUGE even on 100% scale in 1920x1080.

![Snapchat-937982852](https://github.com/Levminer/authme/assets/9919010/33f45d13-7058-4a0f-a966-e3fd2f79cc52)
