### ISSUE TITLE
Please update the snap package in Ubuntu Software

### ISSUE THREAD

**Issue by hmvago** [Levminer/authme#281]
I'm using this application (thank you) under Ubuntu Destopo Linux.
Tha snap package is a little bit old. 
Could you please update the snap package to the last version?

Thank you very much.
Hernan

![image](https://github.com/Levminer/authme/assets/38031980/35ffff81-88e2-4551-87e2-334ca820ce47)

**Comment by Levminer** [comment]
Hi! Tauri currenty doesn't support snap. More info: https://github.com/tauri-apps/tauri/issues/4402

Please use deb/appimage: https://github.com/Levminer/authme/releases
