### ISSUE TITLE
[Documentation] [FAQ entry] Is a smartphone required for authme?

### ISSUE THREAD

**Issue by rubyFeedback** [Levminer/authme#282]
Is a smartphone required for authme?

Could the main README or some linked-in FAQ entry explain this?

Right now I don't know how any of that works and I don't have a smartphone,
which actually means I am left out of more and more services now ever since
github made code-contribution mandatory via 2FA.

**Comment by Levminer** [comment]
No phone required for Authme.

You can import a 2FA code from an image or screenshot in Authme, like you would do it on a phone.

Its explained inside the app, maybe it should be explained in the README more.
