### ISSUE TITLE
Unexpected Token

### ISSUE THREAD

**Issue by BYLance** [Levminer/authme#285]
Good day to you. I am making this report about my issues with Authme for the past few months. Currently, I am unable to open the app due to a so-called "syntax error", which tells me it has an unexpected token regarding my program. You may be wondering why I could've just uninstalled it and install it again, but there are some codes saved there before that I already removed from my current authenticator list, in which I do need it again. Also, I am unsure if whether or not the codes will be lost if I do uninstall the app from my computer. If you can find a solution for my problem, I would be so grateful for your service. That's all, and have a good day. :)
![image](https://github.com/Levminer/authme/assets/158757373/a23970cb-2383-4ea2-a434-89e44001de1e)

**Comment by Levminer** [comment]
Hi!

You are using Authme 2, which is not supported. You can safely reinstall Authme. Your codes, settings and  password are stored in `%appdata%/levminer/authme`. 

After You can export your codes and import them to Authme 3, more info: https://github.com/Levminer/authme?tab=readme-ov-file#contributing-and-development

**Comment by BYLance** [comment]
Hello again, @Levminer 

First of all, thank you for your response. So far, I was able to locate the coding for my codes in the data stored in the system. However, I am confused on what file I should import to the application to get my codes back. I did try to import the file named "codes" to the app to try and see if it'll work. It said that the codes were successfully imported, but the codes didn't show up on the list. Anyhow, I hope you can assist me in this problem as far as you can. That's all, and have a good day.

**Comment by Levminer** [comment]
Okay, looks like you donwloaded Authme 3, but first you need to install Authme 2 again, then export your codes, delete Authme 2 and then install Authme 3 and import your codes.

The file you tried to import is encrytped (codes) with your password (settings)

**Comment by BYLance** [comment]
> Okay, looks like you donwloaded Authme 3, but first you need to install Authme 2 again, then export your codes, delete Authme 2 and then install Authme 3 and import your codes.
> 
> The file you tried to import is encrytped (codes) with your password (settings)

Okay, where can I download Authme 2? Since I'm kind of conflicted to know how to download a previous version of the app.

**Comment by Levminer** [comment]
> > Okay, looks like you donwloaded Authme 3, but first you need to install Authme 2 again, then export your codes, delete Authme 2 and then install Authme 3 and import your codes.
> > The file you tried to import is encrytped (codes) with your password (settings)
> 
> Okay, where can I download Authme 2? Since I'm kind of conflicted to know how to download a previous version of the app.

You can use this link: https://github.com/Levminer/authme/releases/download/3.3.5/authme-3.3.5-windows-x64-installer.exe

**Comment by BYLance** [comment]
> > > Okay, looks like you donwloaded Authme 3, but first you need to install Authme 2 again, then export your codes, delete Authme 2 and then install Authme 3 and import your codes.
> > > The file you tried to import is encrytped (codes) with your password (settings)
> > 
> > 
> > Okay, where can I download Authme 2? Since I'm kind of conflicted to know how to download a previous version of the app.
> 
> You can use this link: https://github.com/Levminer/authme/releases/download/3.3.5/authme-3.3.5-windows-x64-installer.exe

Thank you! I will try to get back to you if anything happens regarding my session. But, do I have to uninstall Authme 3 before I install Authme 2 or can they both exist within the system?

**Comment by Levminer** [comment]
> > > > Okay, looks like you donwloaded Authme 3, but first you need to install Authme 2 again, then export your codes, delete Authme 2 and then install Authme 3 and import your codes.
> > > > The file you tried to import is encrytped (codes) with your password (settings)
> > > 
> > > 
> > > Okay, where can I download Authme 2? Since I'm kind of conflicted to know how to download a previous version of the app.
> > 
> > 
> > You can use this link: https://github.com/Levminer/authme/releases/download/3.3.5/authme-3.3.5-windows-x64-installer.exe
> 
> Thank you! I will try to get back to you if anything happens regarding my session. But, do I have to uninstall Authme 3 before I install Authme 2 or can they both exist within the system?

Authme 4 and Authme 3 can exist side by side. (I sent you a link for Authme 3 which is compatible with Authme 2)
I know its a little confusing, sorry about that.

**Comment by BYLance** [comment]
> > > > > Okay, looks like you donwloaded Authme 3, but first you need to install Authme 2 again, then export your codes, delete Authme 2 and then install Authme 3 and import your codes.
> > > > > The file you tried to import is encrytped (codes) with your password (settings)
> > > > 
> > > > 
> > > > Okay, where can I download Authme 2? Since I'm kind of conflicted to know how to download a previous version of the app.
> > > 
> > > 
> > > You can use this link: https://github.com/Levminer/authme/releases/download/3.3.5/authme-3.3.5-windows-x64-installer.exe
> > 
> > 
> > Thank you! I will try to get back to you if anything happens regarding my session. But, do I have to uninstall Authme 3 before I install Authme 2 or can they both exist within the system?
> 
> Authme 4 and Authme 3 can exist side by side. (I sent you a link for Authme 3 which is compatible with Authme 2) I know its a little confusing, sorry about that.

Okay, so I downloaded the previous Authme, but it states the same error message when I tried to open it. What seems to be the problem?

**Comment by Levminer** [comment]
> > > > > > Okay, looks like you donwloaded Authme 3, but first you need to install Authme 2 again, then export your codes, delete Authme 2 and then install Authme 3 and import your codes.
> > > > > > The file you tried to import is encrytped (codes) with your password (settings)
> > > > > 
> > > > > 
> > > > > Okay, where can I download Authme 2? Since I'm kind of conflicted to know how to download a previous version of the app.
> > > > 
> > > > 
> > > > You can use this link: https://github.com/Levminer/authme/releases/download/3.3.5/authme-3.3.5-windows-x64-installer.exe
> > > 
> > > 
> > > Thank you! I will try to get back to you if anything happens regarding my session. But, do I have to uninstall Authme 3 before I install Authme 2 or can they both exist within the system?
> > 
> > 
> > Authme 4 and Authme 3 can exist side by side. (I sent you a link for Authme 3 which is compatible with Authme 2) I know its a little confusing, sorry about that.
> 
> Okay, so I downloaded the previous Authme, but it states the same error message when I tried to open it. What seems to be the problem?

Can you send me your codes and settings in email? authme@levminer.com
I think your settings might be corrupted.

**Comment by BYLance** [comment]
> > > > > > > Okay, looks like you donwloaded Authme 3, but first you need to install Authme 2 again, then export your codes, delete Authme 2 and then install Authme 3 and import your codes.
> > > > > > > The file you tried to import is encrytped (codes) with your password (settings)
> > > > > > 
> > > > > > 
> > > > > > Okay, where can I download Authme 2? Since I'm kind of conflicted to know how to download a previous version of the app.
> > > > > 
> > > > > 
> > > > > You can use this link: https://github.com/Levminer/authme/releases/download/3.3.5/authme-3.3.5-windows-x64-installer.exe
> > > > 
> > > > 
> > > > Thank you! I will try to get back to you if anything happens regarding my session. But, do I have to uninstall Authme 3 before I install Authme 2 or can they both exist within the system?
> > > 
> > > 
> > > Authme 4 and Authme 3 can exist side by side. (I sent you a link for Authme 3 which is compatible with Authme 2) I know its a little confusing, sorry about that.
> > 
> > 
> > Okay, so I downloaded the previous Authme, but it states the same error message when I tried to open it. What seems to be the problem?
> 
> Can you send me your codes and settings in email? [authme@levminer.com](mailto:authme@levminer.com) I think your settings might be corrupted.

Sure, but I am also trusting you to handle my personal information confidentially. Thank you so much!

**Comment by Levminer** [comment]
> > > > > > > > Okay, looks like you donwloaded Authme 3, but first you need to install Authme 2 again, then export your codes, delete Authme 2 and then install Authme 3 and import your codes.
> > > > > > > > The file you tried to import is encrytped (codes) with your password (settings)
> > > > > > > 
> > > > > > > 
> > > > > > > Okay, where can I download Authme 2? Since I'm kind of conflicted to know how to download a previous version of the app.
> > > > > > 
> > > > > > 
> > > > > > You can use this link: https://github.com/Levminer/authme/releases/download/3.3.5/authme-3.3.5-windows-x64-installer.exe
> > > > > 
> > > > > 
> > > > > Thank you! I will try to get back to you if anything happens regarding my session. But, do I have to uninstall Authme 3 before I install Authme 2 or can they both exist within the system?
> > > > 
> > > > 
> > > > Authme 4 and Authme 3 can exist side by side. (I sent you a link for Authme 3 which is compatible with Authme 2) I know its a little confusing, sorry about that.
> > > 
> > > 
> > > Okay, so I downloaded the previous Authme, but it states the same error message when I tried to open it. What seems to be the problem?
> > 
> > 
> > Can you send me your codes and settings in email? [authme@levminer.com](mailto:authme@levminer.com) I think your settings might be corrupted.
> 
> Sure, but I am also trusting you to handle my personal information confidentially. Thank you so much!

Of course, if you selected require password when opening Authme your codes are encrypted anyway.

**Comment by BYLance** [comment]
> > > > > > > > > Okay, looks like you donwloaded Authme 3, but first you need to install Authme 2 again, then export your codes, delete Authme 2 and then install Authme 3 and import your codes.
> > > > > > > > > The file you tried to import is encrytped (codes) with your password (settings)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Okay, where can I download Authme 2? Since I'm kind of conflicted to know how to download a previous version of the app.
> > > > > > > 
> > > > > > > 
> > > > > > > You can use this link: https://github.com/Levminer/authme/releases/download/3.3.5/authme-3.3.5-windows-x64-installer.exe
> > > > > > 
> > > > > > 
> > > > > > Thank you! I will try to get back to you if anything happens regarding my session. But, do I have to uninstall Authme 3 before I install Authme 2 or can they both exist within the system?
> > > > > 
> > > > > 
> > > > > Authme 4 and Authme 3 can exist side by side. (I sent you a link for Authme 3 which is compatible with Authme 2) I know its a little confusing, sorry about that.
> > > > 
> > > > 
> > > > Okay, so I downloaded the previous Authme, but it states the same error message when I tried to open it. What seems to be the problem?
> > > 
> > > 
> > > Can you send me your codes and settings in email? [authme@levminer.com](mailto:authme@levminer.com) I think your settings might be corrupted.
> > 
> > 
> > Sure, but I am also trusting you to handle my personal information confidentially. Thank you so much!
> 
> Of course, if you selected require password when opening Authme your codes are encrypted anyway.

Sorry for the late reply. I've sent it just now. Thank you. :) I may be gone for a while since there's something I need to do. Have a nice day.

**Comment by Levminer** [comment]
Can you send your log files? I just remember it contains your settings which might help. `%appdata%/levminer/authme/logs`
