### ISSUE TITLE
Authme Mobile App

### ISSUE THREAD

**Issue by 4troDev** [Levminer/authme#286]
### Before the feature request.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a feature request that matches the one I want to file, without success.

### Your feature request related to the problem

An AuthMe mobile app that can be seamlessly linked to the desktop app, similar to Authy.

### Describe the solution you'd like or alternatives you've considered

I'm looking for a solution for desktop authentication following Authy's discontinuation. A mobile AuthMe app could be a valuable alternative, addressing the need for a seamless desktop-mobile authentication experience.

### Additional information

I'd appreciate a mobile app for AuthMe that can securely link with the desktop version. This would help ensure a smooth transition following the discontinuation of Authy's desktop app. Having both platforms integrated would enhance user experience and security.

**Comment by Levminer** [comment]
About mobile: Authme had a web version (With PWA support, so it can be installed on phones) But it wasn't really used.

About syncing: I'v been thinking about creating a p2p secure sync, but it would be a payed service. And I don't think many people would pay, let's say 3$/month just to sync 2FA codes.

But let me know what you think and other sugesstions are welcome.

**Comment by 4troDev** [comment]
$3/month sounds reasonable for a secure sync service, especially considering it's only $36 a year. Offering a free version with banner ads is a smart approach to attract a bigger audience while generating some revenue. Users who prefer an ad-free experience could then opt for the paid version, enjoying better support and additional features. This tiered model provides flexibility for users with different preferences.

**Comment by 4troDev** [comment]
some features that could be in the premium is the device code sync in more than one device backup and restore customization maybe third party apps integration letting people have multiple accounts per device letting people delete their data from the app if their phone gets stolen code sharing emergency code recovery and stuff like that other apps don't offer stuff like that and if they do they have them under a paywall that could be over 30 dollars a month also password generation

**Comment by partha51613** [comment]
I don't think there is a demand for paid apps. Free apps like Aegis/2FAS/GoogleAuth works well on multiple devices.

**Comment by 4troDev** [comment]
> I don't think there is a demand for paid apps. Free apps like Aegis/2FAS/GoogleAuth works well on multiple devices.
> 
> 

that might be the case where you are but not here also GoogleAuth in my experience is the worse auth is only for mobiles and half of the times it didn't work and you couldn't even transfer the codes when changing to a new phone you had to restart all your codes again
