### ISSUE TITLE
(BUG) What kind of app has dev made? Can you tell me how to import the backup brought in from apps like Authenticator Pro, 2FAs Auth, auth, Aegis, MS Authenticator because I cant bring them in your app?

### ISSUE THREAD

**Issue by ghost** [Levminer/authme#287]
### Before the bug report.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a bug that matches the one I want to file, without success.

### Authme/System information

Authme: 5.0.0 

Tauri: 1.5.4
Chromium: 121.0.0.0

OS version: Windows x64 LTSC
Hardware info: Intel Core i7 CPU  8 GB RAM

Release date: 2024. February 13.
Build number: release.240213.163558

Created by: Lőrik Levente

### Authme log

[AUTHME LOG] (2024. 02. 17. 6:51:51) Authme 5.0.0 release.240213.163558
[AUTHME LOG] (2024. 02. 17. 6:51:51) Path changed: /
[AUTHME LOG] (2024. 02. 17. 6:56:49) Path changed: /confirm
[AUTHME LOG] (2024. 02. 17. 6:56:57) Path changed: /codes
[AUTHME LOG] (2024. 02. 17. 6:59:06) Path changed: /import
[AUTHME LOG] (2024. 02. 17. 7:02:32) Path changed: /codes
[AUTHME LOG] (2024. 02. 17. 7:02:33) Path changed: /import
[AUTHME LOG] (2024. 02. 17. 7:03:33) Path changed: /settings

### Describe the bug

I am not able to bring the exported backup of the 2FAs I have done from apps like Authenticator Pro, 2FAs Auth, auth, Aegis, MS Authenticator because I cant bring them in your app on windows.

### To reproduce

Did a backup from those aforementioned apps in the multiple formats and brought in to my windows device to bring them in (aka import) in Authme app.

### Additional information

(BUG) What kind of app has dev made? Can you tell me how to import the backup brought in from apps like Authenticator Pro, 2FAs Auth, auth, Aegis, MS Authenticator because I can't bring them in your app? Has dev checked it in real-time with certain apps because some of us do have a backups and want it to bring to another device for easy access and recently, my mobile died randomly for 6 days and realized having a backup on desktop is needed if this occurs again.

**Comment by Levminer** [comment]
You can see on the import page that **Google Authenticator** and **TOTP** (Scanning the QR code that you are provided when setting up 2FA in your Google, Facebook, etc. account) are supported.

**Comment by ghost** [comment]
> You can see on the import page that **Google Authenticator** and **TOTP** (Scanning the QR code that you are provided when setting up 2FA in your Google, Facebook, etc. account) are supported.

As I said clearly before in the post. None of the options are working with your app. I have checked them thoroughly. You seems to have read nothing I wrote.

**Comment by Levminer** [comment]
What codes did you try to import? Only Google Authenticator and TOTP works. You can't import Authenticator Pro, 2FAs Auth, auth, Aegis, MS Authenticator

**Comment by ghost** [comment]
> What codes did you try to import? Only Google Authenticator and TOTP works. You can't import Authenticator Pro, 2FAs Auth, auth, Aegis, MS Authenticator

that is what I said in the title.

**Comment by Levminer** [comment]
2FAS support tracked at: #288 
Aegis support tracked at: #264 
Others are not currently planned.
