### ISSUE TITLE
Import from 2FAS Authenticator

### ISSUE THREAD

**Issue by Levminer** [Levminer/authme#288]
Import file format: https://github.com/twofas/2fas-android/issues/117

**Comment by sameer4** [comment]
@Levminer not working for me here's a video.. https://www.loom.com/share/f47cf434ba354beea9c6ffa7eb799d82?sid=45f0b2a7-b781-45a0-84e4-b422724c99ae


am i missing something? i exported backup without password.

**Comment by Levminer** [comment]
> @Levminer not working for me here's a video.. https://www.loom.com/share/f47cf434ba354beea9c6ffa7eb799d82?sid=45f0b2a7-b781-45a0-84e4-b422724c99ae
> 
> am i missing something? i exported backup without password.

Thanks for the report!

- Can you send the log file when you tried to import the codes (Settings > Logs)? 
- You can also send your backup file, just delete the secret values. 
- Also Authme only support TOTP, what type of codes you are trying to import?

**Comment by frankbret** [comment]
Trying to import 2fas iOS 5.3.5 backup export (without password).
[Backup_2024-04-09_blank.2fas.json](https://github.com/Levminer/authme/files/14922803/Backup_2024-04-09_blank.2fas.json)

[AUTHME LOG] (2024. 04. 09. 14:35:12) Authme 5.1.0 alpha.240401.133357
[AUTHME LOG] (2024. 04. 09. 14:35:12) Path changed: /
[AUTHME LOG] (2024. 04. 09. 14:35:12) Path changed: /codes
[AUTHME LOG] (2024. 04. 09. 14:35:13) Path changed: /import
[AUTHME LOG] (2024. 04. 09. 14:35:21) Path changed: /codes
[AUTHME ERROR] (2024. 04. 09. 14:35:21) Failed to generate TOTP code from secret
[AUTHME ERROR] (2024. 04. 09. 14:35:21) Unknown runtime error occurred: TypeError: Cannot read properties of undefined (reading 'names')

In the UI :
Failed to generate TOTP code from secret.
Make sure you import file is correct!

Thank you for your invaluable work !

**Comment by Levminer** [comment]
> Trying to import 2fas iOS 5.3.5 backup export (without password). [Backup_2024-04-09_blank.2fas.json](https://github.com/Levminer/authme/files/14922803/Backup_2024-04-09_blank.2fas.json)
> 
> [AUTHME LOG] (2024. 04. 09. 14:35:12) Authme 5.1.0 alpha.240401.133357 [AUTHME LOG] (2024. 04. 09. 14:35:12) Path changed: / [AUTHME LOG] (2024. 04. 09. 14:35:12) Path changed: /codes [AUTHME LOG] (2024. 04. 09. 14:35:13) Path changed: /import [AUTHME LOG] (2024. 04. 09. 14:35:21) Path changed: /codes [AUTHME ERROR] (2024. 04. 09. 14:35:21) Failed to generate TOTP code from secret [AUTHME ERROR] (2024. 04. 09. 14:35:21) Unknown runtime error occurred: TypeError: Cannot read properties of undefined (reading 'names')
> 
> In the UI : Failed to generate TOTP code from secret. Make sure you import file is correct!
> 
> Thank you for your invaluable work !

Thanks for reaching out!
In your file the link is broken:

`otpauth:\/\/totp\/Leaseweb:blablabla@gmail.com?secret=[hidden]&issuer=Leaseweb` should be `otpauth://totp/Leaseweb:blablabla@gmail.com?secret=[hidden]&issuer=Leaseweb`

**Comment by frankbret** [comment]
Sorry, don't work, same problem with all backslash not escaped.
Probably the iOS version of 2fas is different of Android ?
I will try to  compare with someone having an Android and check if https://github.com/twofas/2fas-ios/commits/main/ change something about formating.

I tried to debug the app bug but my vscode don't want to start in debugging with nvs :-(

**Comment by Levminer** [comment]
> Sorry, don't work, same problem with all backslash not escaped. Probably the iOS version of 2fas is different of Android ? I will try to compare with someone having an Android and check if https://github.com/twofas/2fas-ios/commits/main/ change something about formating.
> 
> I tried to debug the app bug but my vscode don't want to start in debugging with nvs :-(

I did some more debugging and it seems like your secrets are not valid. The file is same with Android and iOS.
Changing `otpauth://totp/Leaseweb:blablabla@gmail.com?secret=[hidden]&issuer=Leaseweb` to `otpauth://totp/Leaseweb:blablabla@gmail.com?secret=bca&issuer=bca` works.

**Comment by frankbret** [comment]
Finally found my bug !  The Backup_YYYY-MM-DD.2fas needs to be edited (json text) and manually replace the [hidden] in the "link": "otpauth://totp/ path by the "secret": "123456" item value, one level higher.
Ok tradeoff for a programmer like me but could be interesting to automatically do it in the import procedure for the others ;-)

Interesting conversation about 2fas interoperability [here](https://www.reddit.com/r/2fas_com/comments/1byvvwm/2fas_export_options/).
