### ISSUE TITLE
Instant crash when opening authme

### ISSUE THREAD

**Issue by CatPieLeaf** [Levminer/authme#290]
### Before the bug report.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a bug that matches the one I want to file, without success.

### Authme/System information

- Authme 5.1.0
- Windows 11 Home 22631.3296
- 12th Gen Intel(R) Core(TM) i7-12700H

### Authme log

No logs, the app just doesnt open, i can't access its settings.

### Describe the bug

The app just doesnt open, instantly crashes and shows nothing. sometimes i see a blank window quickly showing and disappearing.

### To reproduce

Open the app.

**Comment by Levminer** [comment]
Thanks for the report!

What's the latest log file? `%LocalAppData%\com.levminer.authme\logs`

**Comment by CatPieLeaf** [comment]
The program did work after windows updated. Windows fault maybe?

**Comment by Levminer** [comment]
If it works now maybe. Probably Windows updated the WebView2 which is used by Authme.
