### ISSUE TITLE
Windows Defender Flagging as PUA

### ISSUE THREAD

**Issue by karmirith** [Levminer/authme#291]
### Before the bug report.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a bug that matches the one I want to file, without success.

### Authme/System information

Authme: 5.1.0 

Tauri: 1.6.1
Chromium: 122.0.0.0

OS version: Windows x64 10.0.22621
Hardware info: 11th Gen Intel Core i5-1145G7  40 GB RAM

Release date: 2024. March 12.
Build number: release.240312.160746

Created by: Lőrik Levente

### Describe the bug

When accessing Authme 5.1.0 in Windows 11 Pro on OS Build 22621.3296 Windows Defender is flagging Authme as a PUAMiner
![image](https://github.com/Levminer/authme/assets/8584840/b82b49d9-f31c-4fbc-a335-2f2232ad1309)

### To reproduce

Install and run Authme

**Comment by Levminer** [comment]
That's strange, never seen anything like this. Maybe it's because only the installer is signed, but the app itself is not signed,
Virus total shows zero viruses: https://www.virustotal.com/gui/file/aa07a875bc96ca850116df263b6c7ba29a13367adfef07188e33c6cf87075e90

**Comment by Levminer** [comment]
Alos this is a Microsoft issue: https://x.com/TauriApps/status/1778088375045566557
