### ISSUE TITLE
Change language in options

### ISSUE THREAD

**Issue by gismomtl** [Levminer/authme#298]
### Before the bug report.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a bug that matches the one I want to file, without success.

### Authme/System information

Authme: 5.1.1 

Tauri: 1.6.5
WebKit: 605.1.15

OS version: macOS arm64 14.4.1
Hardware info: Apple M1 16 GB RAM

Release date: 2024. May 14.
Build number: release.240514.110205

Created by: Lőrik Levente

### Describe the bug

I've tested on MacOS and Windows with  v5.x with english OS.
But after starting the new version,  I don't see the language feature to change from English to French

On Windows running with French localization, interface is in French but it can't be change in English neither
Is there a way to specify language during installation?
Is there a way to add language selection in the option menu?

### To reproduce

no option during installation neither in the option menu

**Comment by gismomtl** [comment]
<img width="1257" alt="Screenshot 2024-05-16 at 8 23 40 PM" src="https://github.com/Levminer/authme/assets/30330032/cde1d82a-5b66-4c18-9715-10c080d47010">
<img width="1222" alt="Screenshot 2024-05-16 at 8 15 33 PM" src="https://github.com/Levminer/authme/assets/30330032/9ed72a5a-d56b-4129-8af5-5ca9344bf0b5">

**Comment by Levminer** [comment]
Yes currently the language depends on the OS. I will add an option to change the language.
