### ISSUE TITLE
Editing codes is not possible

### ISSUE THREAD

**Issue by jkischel** [Levminer/authme#300]
### Before the bug report.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a bug that matches the one I want to file, without success.

### Authme/System information

5.1.1

### Describe the bug

It's no more possible to edit name and description.

### To reproduce

- click on 'edit' of an existing code
- click the edit button right of the code you want to edit
-> Name field can be edited, but not the description
- click the 'edit' button of that line again

-> all looks fine so far.
- Click on "Codes"
-> nothing has been edited. The entry has the same name as before, but not the new one.

**Comment by Levminer** [comment]
Thanks for the report! I noticed it too, will be fixed in the next version.
