### ISSUE TITLE
Fix sorting codes with duplicate issuers

### ISSUE THREAD

**Issue by JOJOVAV** [Levminer/authme#302]
### Before the bug report.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a bug that matches the one I want to file, without success.

### Authme/System information

Authme: 5.1.1 

Tauri: 1.6.5
Chromium: 125.0.0.0

OS version: Windows x64 10.0.19044
Hardware info: AMD Ryzen 7 5800H with Radeon Graphics  15 GB RAM

Release date: 2024. May 14.
Build number: release.240514.110310

Created by: Lőrik Levente

### Describe the bug

The layout is not correct resulting in bad copy of the correct code.
The sorting itself is also not correct.
If you want a grid and sort codes in alphabetic order, the layout is placed in list and the description is also copied multiple times.

### To reproduce

In settings enable code description,
have grid layout
sort code either with A-Z or Z-A

### Additional information

I have multiple codes from the same system like microsoft, google or discord.

**Comment by Levminer** [comment]
Can you attach some screenshots?

**Comment by Levminer** [comment]
Should be fixed by: 25e7c8626885e2d36efd7d6bf79d3f861f1cb208
