### ISSUE TITLE
Codes not valid after windows get restarted.

### ISSUE THREAD

**Issue by bluedream0829** [Levminer/authme#305]
### Before the bug report.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a bug that matches the one I want to file, without success.

### Authme/System information

Authme: 5.2.0 

Tauri: 1.6.8
Chromium: 126.0.0.0

OS version: Windows x64 10.0.17763
Hardware info:  Intel Xeon CPU E5-2690 v2  4 GB RAM

Release date: 2024. June 18.
Build number: release.240618.083908

### Authme log

[AUTHME LOG] (2024. 06. 19. 21:24:55) Path changed: /confirm
[AUTHME LOG] (2024. 06. 19. 21:24:55) Authme 5.2.0 release.240618.083908
[AUTHME LOG] (2024. 06. 19. 21:25:09) Path changed: /codes
[AUTHME LOG] (2024. 06. 19. 21:29:07) Path changed: /settings

### Describe the bug

Once i reboot windows system, Authme asked me update new version.
So, i updated. then all the codes are not working.

### To reproduce

Once i reboot windows system, Authme asked me update new version.
So, i updated. then all the codes are not working.

**Comment by Levminer** [comment]
Are you using sort codes A-Z or Z-A in the settings?

**Comment by bluedream0829** [comment]
No, i don't use.

**Comment by Levminer** [comment]
Can you check in the previous logs what version did you use before the update?

**Comment by bluedream0829** [comment]
I used 5.1.0

**Comment by Levminer** [comment]
If you install 5.1.0 does the issue persist? https://github.com/Levminer/authme/releases/download/5.1.0/authme-5.1.0-windows-x64.msi
