### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by michalsalamucha** [Levminer/authme#306]
### Before the feature request.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a feature request that matches the one I want to file, without success.

### Your feature request related to the problem

Please add the language translation to the software

### Describe the solution you'd like or alternatives you've considered

//tłumaczenie na język polski 
//translation into Polish
import { localeEN } from "@utils/language/en"

export const localeDE: typeof localeEN = {
{
    "common": {
        "confirm": "Potwierdź",
        "continue": "Kontynuuj",
        "cancel": "Anuluj",
        "close": "Zamknij",
        "copy": "Kopiuj",
        "copied": "Skopiowano",
        "moreOptions": "Więcej opcji",
        "name": "Nazwa",
        "description": "Opis",
        "edit": "Edytuj",
        "delete": "Usuń"
    },
    "menu": {
        "codes": "Kody",
        "import": "Importuj",
        "export": "Eksportuj",
        "edit": "Edytuj",
        "settings": "Ustawienia",
        "show": "Pokaż Authme",
        "exit": "Zamknij Authme"
    },
    "landing": {
        "welcome": "Witamy!",
        "gettingStarted": "Pierwsze kroki",
        "gettingStartedText": "Wybierz, jak chcesz używać Authme.",
        "passwordAuth": "Uwierzytelnianie hasłem",
        "passwordAuthText": "Musisz wpisać hasło za każdym razem, gdy uruchamiasz Authme.",
        "noAuth": "Brak uwierzytelniania",
        "noAuthText": "Jeśli nie chcesz wpisywać hasła za każdym razem, gdy uruchamiasz Authme.",
        "hardwareAuth": "Uwierzytelnianie sprzętowe",
        "hardwareAuthText": "Potwierdź ważne działania za pomocą Windows Hello, Touch ID lub dowolnego klucza sprzętowego zgodnego z WebAuthn.",
        "createPass": "Utwórz hasło",
        "createPassText": "Utwórz silne hasło, aby zaszyfrować swoje kody.",
        "password": "Hasło",
        "confirmPassword": "Potwierdź hasło",
        "chooseDifferent": "Wybierz inne uwierzytelnianie",
        "chooseDifferentText": "Wróć do poprzedniej strony i wybierz inną metodę uwierzytelniania.",
        "goBack": "Wróć",
        "dialog": {
            "passwordsNotMatch": "Hasła się nie zgadzają. \n\nProszę spróbować ponownie!",
            "passwordMinLength": "Minimalna długość hasła to 8 znaków. \n\nProszę spróbować ponownie!",
            "passwordMaxLength": "Maksymalna długość hasła to 64 znaki. \n\nProszę spróbować ponownie!",
            "commonPassword": "To hasło znajduje się na liście 1000 najczęstszych haseł. Proszę wybrać bezpieczniejsze hasło!"
		},
	},
    "confirm": {
        "welcomeBack": "Witamy ponownie!",
        "confirmPassword": "Potwierdź hasło",
        "confirmPasswordText": "Proszę wprowadzić hasło, aby kontynuować.",
        "password": "Hasło",
        "forgotPassword": "Zapomniałeś hasła?",
        "forgotPasswordText": "Twoje kody są chronione przez hasło. Jeśli zapomnisz hasła, stracisz dostęp do swoich kodów.",
        "dialog": {
            "wrongPassword": "Błędne hasło! \n\nProszę spróbować ponownie!"
		},
	},
    "codes": {
        "importCodes": "Importuj swoje kody 2FA",
        "importCodesText": "Importuj swoje istniejące kody 2FA na stronie Import.",
        "importCodesButton": "Importuj kody",
        "noSearchResultsFound": "Nie znaleziono wyników wyszukiwania",
        "noSearchResultsFoundText": "Nie znaleziono wyników wyszukiwania dla",
        "dialog": {
            "noSaveFileFound": "Nie znaleziono pliku zapisu. \n\nPrzejdź do strony kodów lub importu i zaimportuj swoje kody!",
            "codesImported": "Kody zaimportowane. \n\nMożesz edytować swoje kody na stronie edycji."
		},
	},
    "import": {
        "supportedTypes": "Obsługiwane typy 2FA",
        "totpQRCode": "TOTP",
        "totpQRCodeText": "Kod QR TOTP to coś, co znajdziesz w większości miejsc, jeśli chcesz skonfigurować 2FA. Składa się z 6 cyfr, które zmieniają się co 30 sekund.",
        "instructions": "Instrukcje",
        "googleAuthQRCode": "Google Authenticator",
        "googleAuthQRCodeText": "Jeśli używasz Google Authenticator, możesz wyeksportować wszystkie swoje istniejące kody i zaimportować je do Authme.",
        "chooseImportMethod": "Wybierz metodę importu",
        "importFromImage": "Importuj z obrazu",
        "importFromImageText": "Wybierz obraz zawierający kompatybilny kod QR.",
        "chooseImageButton": "Wybierz obraz",
        "enterSecretManually": "Wprowadź klucz konfiguracji",
        "enterSecretManuallyText": "Wprowadź klucz tajny TOTP i nazwę.",
        "enterSecretManuallyButton": "Skonfiguruj klucz",
        "screenCapture": "Przechwyć ekran",
        "screenCaptureText": "Przechwyć kompatybilny kod QR z ekranu.",
        "screenCaptureButton": "Przechwyć ekran",
        "webcam": "Kamera internetowa",
        "webcamText": "Użyj kamery internetowej do zeskanowania kompatybilnego kodu QR.",
        "webcamButton": "Użyj kamery internetowej",
        "authme": "Authme",
        "authmeText": "Importuj wszystkie swoje kody z Authme.",
        "authmeFile": "Plik Authme",
        "authmeFileText": "Importuj wszystkie kody z istniejącego pliku importu Authme, który wyeksportowałeś z Authme.",
        "authmeFileButton": "Wybierz plik",
        "twoFasAuth": "2FAS Authenticator",
        "twoFasAuthText": "Importuj wszystkie kody z kopii zapasowej 2FAS Authenticator.",
        "twoFasFile": "Plik kopii zapasowej 2FAS (bez hasła)",
        "twoFasFileText": "Importuj wszystkie kody z istniejącego pliku kopii zapasowej 2FAS bez hasła.",
        "twoFasFileButton": "Wybierz plik",
        "aegisAuth": "Aegis Authenticator",
        "aegisAuthText": "Importuj wszystkie kody z sejfu Aegis.",
        "aegisFile": "Plik sejfu Aegis (bez hasła)",
        "aegisFileText": "Importuj wszystkie kody z istniejącego pliku sejfu Aegis bez hasła.",
        "aegisFileButton": "Wybierz plik",
        "captureScreenTitle": "Import przechwytywania ekranu",
        "captureScreenWaiting": "Oczekiwanie na kod QR...",
        "manualEntry": "Skonfiguruj klucz",
        "manualEntryText": "Proszę wprowadzić nazwę i klucz tajny 2FA.",
        "manualEntryName": "Nazwa (wymagana)",
        "manualEntrySecret": "Tajny klucz (wymagany)",
        "manualEntryDescription": "Opis",
        "googleAuthTutorial": ["Eksportuj kody 2FA z aplikacji Google Authenticator: Stuknij w ikonę hamburgera w lewym górnym rogu ekranu: Transferuj konta > Eksportuj konta", "Zapisz kod(y) QR migracji za pomocą zrzutu ekranu lub zrób zdjęcie innym telefonem, jeśli korzystasz z Androida. Przenieś te obrazy na komputer", "W Authme, przejdź do strony Import: Pasek boczny > Import", "Kliknij przycisk Wybierz obrazy i wybierz obraz(y) przeniesione z telefonu"],
        "totpTutorial": ["Przejdź na stronę internetową, na której chcesz skonfigurować 2FA", "Zrób zrzut ekranu (kombinacja klawiszy Windows + Shift + S na Windows, Cmd + Shift + 3 na macOS) kodu QR i zapisz obraz", "W Authme, przejdź do strony Import: Pasek boczny > Import", "Kliknij przycisk Wybierz obrazy i wybierz obraz"],
        "authmeTutorial": ["W Authme przejdź do strony Eksport i wybierz Eksportuj plik Authme", "Możesz zaimportować ten plik w Authme na stronie Import"],
        "aegisTutorial": ["Stuknij w ikonę hamburgera w prawym górnym rogu ekranu: Ustawienia > Import i eksport > Eksport", "Wybierz format JSON Aegis i odznacz pole Szyfrowanie, a następnie wyeksportuj swój sejf", "Przenieś plik na komputer i zaimportuj go do Authme"],
        "twoFasTutorial": ["Stuknij w ustawienia na pasku nawigacyjnym: Kopia zapasowa 2FAS > Eksportuj do pliku", "Zaznacz pole Eksportuj plik bez hasła i stuknij Eksportuj", "Przenieś plik na komputer i zaimportuj go do Authme"]
    },
    "export": {
        "exportCodes": "Eksportuj kody",
        "exportAuthmeFile": "Eksportuj plik Authme",
        "exportAuthmeFileText": "Idealny do importu dla Authme lub innych aplikacji Authme.",
        "exportHTMlFile": "Eksportuj plik HTML",
        "exportHTMlFileText": "Idealny do skanowania kodów QR lub jako kopia zapasowa bezpieczeństwa.",
        "exportFileButton": "Eksportuj plik"
    },
    "edit": {
        "editCodes": "Edytuj kody",
        "dialog": {
            "saveChanges": "Czy chcesz zapisać zmiany?",
            "deleteCode": "Czy na pewno chcesz usunąć ten kod?"
		},
	},
    "settings": {
        "general": "Ogólne",
        "launchOnStartup": "Uruchom przy starcie",
        "launchOnStartupText": "Automatycznie uruchamiaj Authme przy starcie systemu w zasobniku systemowym.",
        "minimizeToTray": "Minimalizuj do zasobnika",
        "minimizeToTrayText": "Podczas zamykania aplikacji Authme nie zostanie zamknięta. Możesz otworzyć Authme z zasobnika systemowego.",
        "optionalAnalytics": "Opcjonalna analityka",
        "optionalAnalyticsText": "Wysyłane dane są całkowicie anonimowe. Wysyłane dane obejmują wersję Authme i informacje o twoim komputerze.",
        "windowCapture": "Przechwytywanie okna",
        "windowCaptureText": "Domyślnie Authme nie może być przechwytywane przez zewnętrzne programy. Jeśli włączysz tę opcję, będzie ona obowiązywać do ponownego uruchomienia Authme.",
        "clearData": "Wyczyść dane",
        "clearDataText": "Wyczyść hasło, kody 2FA i wszystkie inne ustawienia. Bądź ostrożny, tej operacji nie można cofnąć!",
        "clearDataButton": "Wyczyść dane",
        "codes": "Kody",
        "codesDescription": "Opis kodów",
        "codesDescriptionText": "Opis kodów 2FA będzie widoczny. Możesz go skopiować po kliknięciu.",
        "blurCodes": "Rozmyj kody",
        "blurCodesText": "Rozmyj zapisane kody. Nadal możesz skopiować kody lub najechać na nie, aby je wyświetlić.",
        "codesLayout": "Układ kodów",
        "codesLayoutText": "Możesz wybrać preferowany układ. Siatka wyświetla więcej elementów i dostosowuje się do rozmiaru ekranu.",
        "sortCodes": "Sortuj kody",
        "sortCodesText": "Możesz wybrać sposób sortowania kodów. Domyślnie kody są sortowane według kolejności importowania.",
        "shortcuts": "Skróty",
        "shortcutsEditButton": "Edytuj",
        "shortcutsResetButton": "Resetuj",
        "shortcutsDeleteButton": "Usuń",
        "about": "O aplikacji",
        "feedback": "Opinie",
        "feedbackText": "Dziękujemy za przekazanie opinii! Proszę zgłaszać problemy lub żądania funkcji na GitHubie lub przez e-mail (authme@levminer.com).",
        "logs": "Logi",
        "logsText": "Możesz wyświetlić logi do debugowania.",
        "showLogsButton": "Pokaż logi",
        "aboutAuthme": "O Authme",
        "aboutAuthmeText": "Informacje o twojej wersji Authme i twoim komputerze."
		},
}

**Comment by michalsalamucha** [comment]
[pl.ts.zip](https://github.com/user-attachments/files/15910405/pl.ts.zip)

**Comment by Levminer** [comment]
Thanks for you work! Please submit a [Pull request ](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)

**Comment by michalsalamucha** [comment]
I don't know if I did it right.  I created a new fork and added the index.ts files, pl.ts

**Comment by Levminer** [comment]
You are on the right track, now go to the branch [you created](https://github.com/michalsalamucha/authmePL/tree/michalsalamucha-Lang_PL). And contribute the changes you made.
