### ISSUE TITLE
Failed to import 2fa file to authme

### ISSUE THREAD

**Issue by OFandoud** [Levminer/authme#307]
### Before the bug report.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a bug that matches the one I want to file, without success.

### Authme/System information

Authme: 5.2.0 

Tauri: 1.6.8
Chromium: 126.0.0.0

OS version: Windows x64 10.0.22631
Hardware info: 11th Gen Intel Core i7-1165G7  16 GB RAM

Release date: 2024. June 18.
Build number: release.240618.083908

Created by: Lőrik Levente

### Authme log

[AUTHME ERROR] (2024. 06. 21. 15:28:03) Unknown runtime error occurred: TypeError: Cannot read properties of undefined (reading 'replaceAll')

### Describe the bug

I can't import 2fa file to authme app and get error.

### To reproduce

I can't import 2fa file to authme app and get error.

**Comment by Levminer** [comment]
Can you share the file, just replace the secret values with xxx or something.

**Comment by eagleeyetom** [comment]
Hi! I'm facing the same issue. Not possible to import 2FAS codes. I have anonymized my secrets and sent it to you via email. I'm also uploading the log.
[authme-2024-07-12-19-57-22.log](https://github.com/user-attachments/files/16198952/authme-2024-07-12-19-57-22.log)

**Comment by Levminer** [comment]
> Hi! I'm facing the same issue. Not possible to import 2FAS codes. I have anonymized my secrets and sent it to you via email. I'm also uploading the log. [authme-2024-07-12-19-57-22.log](https://github.com/user-attachments/files/16198952/authme-2024-07-12-19-57-22.log)

Thank you!

I've identified two issues:

1. Manual imports didn't work
2. Some links didn't include an issuer

Will be fixed in the next release!
