### ISSUE TITLE
Improved password verification

### ISSUE THREAD

**Issue by KaiLDK72** [Levminer/authme#308]
### Before the bug report.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a bug that matches the one I want to file, without success.

### Authme/System information

Authme: 5.2.1 

Tauri: 1.7.1
WebKit: 17.0

OS version: Ubuntu x64 24.4.0
Hardware info: Intel Core i5-3340M CPU  8 GB RAM

Release date: 2024. July 09.
Build number: release.240709.151930

Created by: Lőrik Levente

### Authme log

Didnt work at all - Pressing the button does nothing.

### Describe the bug

When entering a password opening the App first time you need to confirm by entering the password again.
If you enter a wrong password at this step, the app mentions that by telling you that the passwords dont match.
The app then proceeds anyways to the login screen what leaves you with a password that you maybe dont know because it uses the wrong entered 1st password.

### To reproduce

Open the app first time. Enter a password and enter a different password.

**Comment by Levminer** [comment]
Thanks for the report!

Should be fixed in the next release.
