### ISSUE TITLE
No encryption in File or wrong status in Exportfile

### ISSUE THREAD

**Issue by KaiLDK72** [Levminer/authme#309]
### Before the bug report.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a bug that matches the one I want to file, without success.

### Authme/System information

Authme: 5.2.1 

Tauri: 1.7.1
WebKit: 17.0

OS version: Ubuntu x64 24.4.0
Hardware info: Intel Core i5-3340M CPU  8 GB RAM

Release date: 2024. July 09.
Build number: release.240709.151930

Created by: Lőrik Levente

### Authme log

Button doesnt work..
When pressing: 
[AUTHME ERROR] (2024. 08. 04. 12:56:22) Unknown runtime error occurred: shell error: failed to open: Scoped shell IO error: exit status: 3

### Describe the bug

Whatever I do (password, no password).
The encryption status inside the export file stays the same:
{
	"role": "codes",
	"encrypted": false,

 I would rather assume that if I provide a password, the backup gets encrypted in any way.

### To reproduce

Export your codes and look at the file.

**Comment by Levminer** [comment]
The export file is not encrypted, and its not a planned feature.
