### ISSUE TITLE
2FAS - Import Error - Cannot read properties of undefined

### ISSUE THREAD

**Issue by Otagamo** [Levminer/authme#310]
### Before the bug report.

- [x] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a bug that matches the one I want to file, without success.

### Authme/System information

Authme 5.2.1

### Authme log

[AUTHME LOG] (2024. 08. 09. 13:58:22) Path changed: /confirm
[AUTHME LOG] (2024. 08. 09. 13:58:22) Authme 5.2.1 release.240709.152047
[AUTHME LOG] (2024. 08. 09. 13:58:34) Path changed: /codes
[AUTHME LOG] (2024. 08. 09. 13:58:36) Path changed: /import
[AUTHME ERROR] (2024. 08. 09. 13:58:45) Unknown runtime error occurred: TypeError: Cannot read properties of undefined (reading 'replaceAll')
[AUTHME LOG] (2024. 08. 09. 14:00:03) Path changed: /codes
[AUTHME LOG] (2024. 08. 09. 14:00:12) Path changed: /edit
[AUTHME LOG] (2024. 08. 09. 14:00:16) Path changed: /export
[AUTHME LOG] (2024. 08. 09. 14:00:17) Path changed: /import
[AUTHME LOG] (2024. 08. 09. 14:00:18) Path changed: /export
[AUTHME LOG] (2024. 08. 09. 14:00:19) Path changed: /import
[AUTHME ERROR] (2024. 08. 09. 14:00:24) Unknown runtime error occurred: TypeError: Cannot read properties of undefined (reading 'replaceAll')
[AUTHME LOG] (2024. 08. 09. 14:01:22) Path changed: /settings
[AUTHME LOG] (2024. 08. 09. 14:02:11) Path changed: /import
[AUTHME ERROR] (2024. 08. 09. 14:02:16) Unknown runtime error occurred: TypeError: Cannot read properties of undefined (reading 'replaceAll')
[AUTHME LOG] (2024. 08. 09. 14:03:52) Path changed: /settings

### Describe the bug

I'm trying to import a 2FAS backup without password, when I select the file nothing happens. No message show in app. The logs shows an error.

### To reproduce

1 - Using the 2FAS Authenticator app, create a backup without password
2 - Using Authme 5.2.1, go to 'Import > 2FAS Authenticator' and select the backup file

### Additional information

The 2FAS backup file contains extra information like Group Names, Custom colors and Custom labels.
I'm not sure if this extra data can generate a bug during the import process. 
For security reasons I can't share my backup file.

**Comment by Otagamo** [comment]
I found a similar issue already opened

**Comment by Otagamo** [comment]
I closed this before there's a similar issue already opened.

**Comment by Levminer** [comment]
Thanks! You can try downloading the pre-release version, let me know if it works: https://nightly.link/Levminer/authme/actions/runs/10273351746

**Comment by Otagamo** [comment]
> Thanks! You can try downloading the pre-release version, let me know if it works: https://nightly.link/Levminer/authme/actions/runs/10273351746

It works now, all codes imported. Thank you

Version used: authme-latest-alpha-windows-x64-installer-portable
