### ISSUE TITLE
Make clear data button more granular

### ISSUE THREAD

**Issue by valentinb102** [Levminer/authme#311]
### Before the feature request.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a feature request that matches the one I want to file, without success.

### Your feature request related to the problem

Currently the clear data button wipes everything. There is no way to specify a subset of data to clear.

### Describe the solution you'd like or alternatives you've considered

A set of checkboxes in a popup so that the user can specify what to clear.

### Additional information

My current workflow is: 

- Create a new OTP in Aegis
- Export Aegis codes
- Clear data in Authme
- Import Aegis codes in Authme

This would speed up the workflow by allowing me to only clear the codes while keeping all other settings.

**Comment by Levminer** [comment]
There's a button in developer mode that clears only the codes, this should be a great addition
