### ISSUE TITLE
Fix Windows code signing

### ISSUE THREAD

**Issue by Otagamo** [Levminer/authme#312]
### Before the bug report.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a bug that matches the one I want to file, without success.

### Authme/System information

Authme 5.2.2
Windows 11 23H2 22631.4037
Chrome 127.0.6533.120

### Describe the bug

Using Chrome 127.0.6533.120 (64 bits) and Windows 11 23H2 22631.4037
Windows Defender is detecting 'Trojan:Win32/CoinMiner.N!cl' in the zip file

If installed, the detection points to "Authme.exe"

### To reproduce
1 - Use Windows 11 23H2 22631.4037
2 - Use Chrome 127.0.6533.120
3 - Download authme-5.2.2-windows-x64.zip (https://github.com/Levminer/authme/releases/download/5.2.2/authme-5.2.2-windows-x64.zip)

**Comment by Levminer** [comment]
Code signing failed on the latest build (5.2.2) so that's why I think defender is angry. Can you check if it works om 5.2.1?

**Comment by Otagamo** [comment]
> Code signing failed on the latest build (5.2.2) so that's why I think defender is angry. Can you check if it works om 5.2.1?

5.2.1 is fine, no virus detection in Windows Defender

About 5.2.2
Windows Defender is detecting sometimes 'Trojan:Script/Phonzy.A!ml' or 'Trojan:Win32/CoinMiner.N!cl'

Virus Total don't detect anything in 'authme-5.2.2-windows-x64.zip'
https://www.virustotal.com/gui/url/c1f1434a442db1a31b93b854c9cc3b676a1fc2fc470611ebfbabb8c3e6af9f59/details

**Comment by XOCODE-OP** [comment]
Can conform with 5.2.2 just got the same Coinminer detection

**Comment by Levminer** [comment]
**Update:** 
Signing the app version 5.2.2 failed because my code signing certificate expired. I'm already contacted Microsoft, maybe they resolve it quickly.

The 5.2.2 version was pulled, if you install 5.2.1 it should work fine. A new version will be released when Microsoft approves the new certificate.

**Comment by michalot** [comment]
So, where can I find 5.2.1 compilation for Windows?

**Comment by Otagamo** [comment]
> So, where can I find 5.2.1 compilation for Windows?

https://github.com/Levminer/authme/releases/tag/5.2.1

**Comment by Levminer** [comment]
Fixed in 5.3.0
