### ISSUE TITLE
webcam: OverconstrainedError: Invalid constraint on Ubuntu 20.04 X86_64 / AppImage 

### ISSUE THREAD

**Issue by frankfletcher** [Levminer/authme#313]
### Before the bug report.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a bug that matches the one I want to file, without success.

### Authme/System information

Authme: 5.2.2 

Tauri: 1.7.1
WebKit: 17.0

OS version: Ubuntu x64 22.4.0
Hardware info: AMD Ryzen 9 3900XT 12-Core Processor 63 GB RAM

Release date: 2024. August 13.
Build number: release.240813.102027

Created by: Lőrik Levente

### Authme log

[AUTHME LOG] (2024. 08. 20. 13:44:56) Authme 5.2.2 release.240813.102027
[AUTHME LOG] (2024. 08. 20. 13:44:56) Path changed: /
[AUTHME LOG] (2024. 08. 20. 13:44:56) Path changed: /codes
[AUTHME ERROR] (2024. 08. 20. 13:44:57) Failed to check for update: the platform `linux-x86_64` was not found on the response `platforms` object
[AUTHME LOG] (2024. 08. 20. 13:45:03) Path changed: /settings
[AUTHME LOG] (2024. 08. 20. 13:45:44) Path changed: /import
[AUTHME ERROR] (2024. 08. 20. 13:45:50) Error occurred while using the webcam: OverconstrainedError: Invalid constraint
[AUTHME LOG] (2024. 08. 20. 13:45:54) Path changed: /settings

### Describe the bug

Any attempt to use the webcam to import codes results in the OverConstrainedError on Ubuntu 20.04, fully updated as of 2020820. 

### To reproduce

1. Open Authme
2. Click IMPORT
3. Click Google Authenticator --> Choose Import Method --> Webcam

### Additional information

```
frank@Firefly-U:bin$ more /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS"

frank@Firefly-U:bin$ uname -a
Linux Firefly-U 5.15.0-118-generic #128-Ubuntu SMP Fri Jul 5 09:28:59 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

```

STDOUT during the error:
```
frank@Firefly-U:bin$ ./authme.appimage 
Gtk-Message: 13:44:55.253: Failed to load module "unity-gtk-module"
Gtk-Message: 13:44:55.256: Failed to load module "unity-gtk-module"

** (authme:536092): WARNING **: 13:44:55.485: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
Gtk-Message: 13:44:55.567: Failed to load module "unity-gtk-module"
Gtk-Message: 13:44:55.569: Failed to load module "unity-gtk-module"
[AUTHME LOG] (2024. 08. 20. 13:44:56) Authme 5.2.2 release.240813.102027
[AUTHME LOG] (2024. 08. 20. 13:44:56) Path changed: /
[AUTHME LOG] (2024. 08. 20. 13:44:56) Path changed: /codes
[AUTHME ERROR] (2024. 08. 20. 13:44:57) Failed to check for update: the platform `linux-x86_64` was not found on the response `platforms` object
[AUTHME LOG] (2024. 08. 20. 13:45:03) Path changed: /settings
[AUTHME LOG] (2024. 08. 20. 13:45:44) Path changed: /import
Video capture was requested but no device was found amongst 0 devices
IntConstraint 1, min -1, max -1, exact -1, ideal 640
IntConstraint 2, min -1, max -1, exact -1, ideal 480
DoubleConstraint 4, min -1.000000, max -1.000000, exact -1.000000, ideal 30.000000
MediaConstraint 5 of type 3
[AUTHME ERROR] (2024. 08. 20. 13:45:50) Error occurred while using the webcam: OverconstrainedError: Invalid constraint
[AUTHME LOG] (2024. 08. 20. 13:45:54) Path changed: /settings
[AUTHME LOG] (2024. 08. 20. 13:47:18) Path changed: /import
[AUTHME LOG] (2024. 08. 20. 13:48:41) Path changed: /idle
```

**Comment by Levminer** [comment]
Couldn't replicate on Ubuntu 24.04

**Comment by jwhipp** [comment]
I am able to replicate this with the Appimage and the Deb on Ubuntu 24.04
![image](https://github.com/user-attachments/assets/448cf7ed-d54c-4fc5-98fb-46ec3afb5833)

Log:
authme-6.0.0-linux-x64.appimage[2345176]: [AUTHME ERROR] (2025. 01. 07. 14:56:45) Error occurred while using the webcam: OverconstrainedError: Invalid constraint
