### ISSUE TITLE
Review size of text and visual elements to better fit screen resolution

### ISSUE THREAD

**Issue by pablolerner** [Levminer/authme#314]
### Before the feature request.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a feature request that matches the one I want to file, without success.

### Your feature request related to the problem

Thanks for the work on this app. It's really useful for me and really like it. One thing I noticed is that for my PC monitor the smallest size of the app screen is too wide and text is too big. I can't comfortably place the app screen next to other apps, while at the same time being able to look at the proper code I need, since it takes up too much space in the PC monitor. The attached screenshot shows the text size difference with other applications in my PC. Please, would you review the size of all visual elements in the app and see how to make them smaller and better fit the screen resolution?

The screenshot is showing a 22 inches monitor with a 1920x1080 resolution.

![imagen](https://github.com/user-attachments/assets/e62a9083-6054-4b9f-a7f2-30d381461eca)

### Describe the solution you'd like or alternatives you've considered

Make the text of the app and all icons and visual elements smaller. At the same time allow for the minimum size of the screen to be smaller. Ideally, the app should be the same size of the OpenVPN screen next to it in the attached screenshot, while at the same time being able to fit several codes to be able to see the one I need.

**Comment by valentinb102** [comment]
I agree this would be very useful. Im thinking changing all font sizes to reference common variables and add buttons to increase/decrease font size. Viewport sizing would also work.

https://css-tricks.com/viewport-sized-typography/
https://developer.mozilla.org/en-US/docs/Web/CSS/calc

**Comment by Levminer** [comment]
In the next version this should be better. Minimum size is now 550px instead of 1000px.

![image](https://github.com/user-attachments/assets/11c2eecf-02a4-4154-8f94-03e9e5d5fa9b)

**Comment by pablolerner** [comment]
Thanks for working on this!
