### ISSUE TITLE
Allow more text for description.

### ISSUE THREAD

**Issue by fbgalaxy5** [Levminer/authme#317]
### Before the feature request.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a feature request that matches the one I want to file, without success.

### Your feature request related to the problem

Please allow more text in description.  Limiting to 40 chars is oddly low like the old Twitter.  Allow 100-200 or more seems do-able, and it does not need to be shown on TOTP screen either.  Right now, when you paste too many characters, it chops off without warning.

### Describe the solution you'd like or alternatives you've considered

There is no alternative.  Allow more text to be kept seems intuitive enough.

### Additional information

n/a

**Comment by Levminer** [comment]
Thats a fair point, should be fixed in the next version!

**Comment by fbgalaxy5** [comment]
Thank you!
