### ISSUE TITLE
Fix 2FAS Invalid URL

### ISSUE THREAD

**Issue by SakulFlee** [Levminer/authme#318]
### Before the bug report.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a bug that matches the one I want to file, without success.

### Authme/System information

Authme 5.3.0 release.240910.164148

### Authme log

[AUTHME LOG] (2024. 09. 17. 21:27:01) Authme 5.3.0 release.240910.164148
[AUTHME LOG] (2024. 09. 17. 21:27:26) Path changed: /import
[AUTHME ERROR] (2024. 09. 17. 21:27:31) Unknown runtime error occurred: TypeError: Failed to construct 'URL': Invalid URL

### Describe the bug

Just tried to import my 2FAS Backup (no password set, freshly exported) into AuthMe and it gives me the error `Unknown runtime error occurred: TypeError: Failed to construct 'URL': Invalid URL`.
I've found https://github.com/Levminer/authme/issues/288#issuecomment-2116261849, but that seems to be referring to a completely different format. I think 2FAS may have changed the export format _again_.

### To reproduce

0. Have a 2FAS account or make one with at least one TOTP Token
1. Export 2FAS Backup (passwordless)
2. Import 2FAS Backup into AuthMe
3. _Observe Error_

### Additional information

I'll include a sanitized 2FAS Backup file below. The mentioned `"link": "otpauth://totp/ path` is no where to be found.

```json
// 2fas-backup.2fas
 {
    "services": [
        {
            "name": "LABEL",
            "secret": "SECRET_KEY",
            "updatedAt": UNIX_TIMESTAMP,
            "serviceTypeID": "UUID",
            "otp": {
                "label": "LABEL",
                "account": "LABEL",
                "issuer": "LABEL",
                "digits": 6,
                "period": 30,
                "algorithm": "SHA1",
                "tokenType": "TOTP",
                "source": "Link"
            },
            "order": {
                "position": 0
            },
            "icon": {
                "selected": "IconCollection",
                "iconCollection": {
                    "id": "UUID"
                }
            }
        },
        ...
    ]
}
```

**Comment by Levminer** [comment]
Can you check the bottom of the file? Should be something like this:

```
    "appVersionName": "5.3.5",
    "appVersionCode": 50305,
    "appOrigin": "ios",
    "schemaVersion": 4,
    "groups": []
```

**Comment by SakulFlee** [comment]
I totally missed the bottom of that file! Sorry about that, here you go:
```json
{
    "services": [
        { ... as above ... },
    ],
    "groups": [],
    "updatedAt": 1726667557361,
    "schemaVersion": 4,
    "appVersionCode": 5000025,
    "appVersionName": "5.4.6",
    "appOrigin": "android"
 }
```

**Comment by Levminer** [comment]
That's strange. It's the same scheme version 4. Not sure how we are gona detect that.

**Comment by SakulFlee** [comment]
I've noticed that, it's weird.
Maybe you can check for the app version instead?

Your example uses 5.3.x.
Mine is 5.4.x.
I don't know when they changed this but maybe checking for "app version ≥
5.4.x" would suffice?
(Assuming your example was a proper one and not a mockup)

On another note: might this be exclusive to Android? I don't have an iOS
device to test, unfortunately.

**Comment by SakulFlee** [comment]
I've just took a look at the 2FAS-Android app on GitHub and as far as I can tell this is the structure used for encoding & decoding backup files: https://github.com/twofas/2fas-android/blob/e97f1a1040eafaed6d5284d54d33403dff215886/data/services/src/main/java/com/twofasapp/data/services/local/model/ServiceEntity.kt
(at least partially, the `services: [ ... ]` bit)

It actually seems like it wasn't changed. The last update is from over a year ago.

**Comment by SakulFlee** [comment]
Just took a look through your source code and I think I identified the issue. It doesn't seem to be a format issue!
Just... some weird backup file I seem to have?

This line: https://github.com/Levminer/authme/blob/d18bf6bacbd72db679541ff41ea4f3a5b6d1f2eb/interface/windows/import/index.ts#L243
1. You are checking if the `tokenType` is `TOTP`. Which it is!
2. You are then checking if `source` is `Link`. Which it also is!
3. You are then trying to read the `service.otp.link`. This field does not exist in my backup file _for some reason_.

Might I suggest checking if that field exists and if not, defaulting back to the else case which seems to generate the image?
Alternatively, you could put a try-catch to make this pass.

I'll see if I can fix it myself.

**Comment by SakulFlee** [comment]
@Levminer I've opened a PR: #320 
Let me know if there is something you need me to change.
There are some issues with the CI, I included those in the PR.

Tried it locally with my "broken" 2FA-Backup file, and it works like a charm now :)
All keys imported 🥳

**Comment by Levminer** [comment]
Thanks for your work!
