### ISSUE TITLE
Azure Defender - Unwanted software detected

### ISSUE THREAD

**Issue by baz-ai** [Levminer/authme#321]
Azure Defender is flagging the authme.exe as unwanted software.  "Redbyrepminer" is being flagged within the software.

Example is attached.
![authme_redbyrepminer](https://github.com/user-attachments/assets/fa14668c-8449-47a9-9dd1-6f7c30931f97)

**Comment by Levminer** [comment]
Hello!

What version of Authme is this? There was a false-positive in the previous version.

**Comment by baz-ai** [comment]
authme-5.3.0-windows-x64.msi

**Comment by Levminer** [comment]
Sorry, but I can't do anything about it. When a new update releases a couple people have to download it to make Windows Defender happy. Everything is signed with a certificate, this is a Microsoft issue.
