### ISSUE TITLE
Authme and synchronisation

### ISSUE THREAD

**Issue by MBNAME12** [Levminer/authme#323]
Does the authme authenticator provide synchronisation of secret keys and TOTP codes across Linux and Windows platforms ?

**Comment by Levminer** [comment]
You can export your codes inside Authme on the export page (.authme file). You can use that export page on Windows, Linux, Mac and web.

**Comment by MBNAME12** [comment]
I am afraid the method of synchronisation of codes between two platforms is
not at all clear to me unfortunately.

How do I import these codes ( inside a .authme file ?) into an Authme
authenticator on another platform ?

E.G.  If I am using Authme on Linux and export codes (inside a .authme file
?) using the Export screen, can I then import those same codes when I am
using Authme on Windows ? If so, which screen do I use to import those
codes ?
