### ISSUE TITLE
Add Language section in the translation

### ISSUE THREAD

**Issue by gismomtl** [Levminer/authme#327]
### Before the feature request.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a feature request that matches the one I want to file, without success.

### Your feature request related to the problem

the current code in settings.svelte contain 

<div>
				<h2>Language</h2>
				<h3>Select your preferred language. By default it will be the system language</h3>
			</div>
			
			the H2 section and the H3 section should be added in the translation file
			

### Describe the solution you'd like or alternatives you've considered

In the en.ts we will have "Language" and "Select your preferred language. By default it will be the system language"
in the fr.ts it will be "Langue" and "Choisissez votre langue préférée. Par défaut ce sera la langue du système"

**Comment by Levminer** [comment]
Thanks! Will be fixed in the next version.
