### ISSUE TITLE
Dependency libwebkit2gtk-4.0-37 Out of Date: libwebkit2gtk >4.0-37 (f.e. v4.1-0) does not work

### ISSUE THREAD

**Issue by 6xthFNGR** [Levminer/authme#329]
### Before the bug report.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a bug that matches the one I want to file, without success.

### Authme/System information

authme 5.3.1 .deb while my system runs Kernel 6.8.0-48 and libwebkit2gtk-4.1-0

### Authme log

"The following packages have unmet dependencies:
 authme : Depends: libwebkit2gtk-4.0-37 but it is not installable"

### Describe the bug

authme .deb installation stops due to requiring libwebkit2gtk-4.0-37 as dependency

### To reproduce

Use f.e. libwebkit2gtk-4.1-0 or anything greater than 4.0-37 in conjunction with authme 5.3.1

### Additional information

Please do not set hard limits for dependencies (libwebkit2gtk **=** 4.0-37) but just define minimum requirements (libwebkit2gtk **>=** 4.0-37) so a user can test if a newer dependency works without breaking authme as well.

Additionaly I would appreciate if no webkit is required at all.
Why do you need it? Is the program rendered via webkit, or do you call for web services?

Thanks ahead

**Comment by Levminer** [comment]
Dependencies are handled by Tauri: https://tauri.app/start/prerequisites/

WebKit is needed beacuse the app is rendered like a browser. No outside calls are made
