### ISSUE TITLE
AppImage misses libgvfs

### ISSUE THREAD

**Issue by 6xthFNGR** [Levminer/authme#330]
### Before the bug report.

- [X] I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a bug that matches the one I want to file, without success.

### Authme/System information

authme-5.3.1-linux-x64.appimage on Ubuntu 24 LTS with Kernel 6.8.0-48

### Authme log

$ ./authme-5.3.1-linux-x64.appimage
-->
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so

apt list \*gvfs\*
Listing... Done
gvfs-backends/noble,now 1.54.0-1ubuntu2 amd64 [installed,automatic]
gvfs-backends/noble 1.54.0-1ubuntu2 i386
gvfs-common/noble,noble,now 1.54.0-1ubuntu2 all [installed,automatic]
gvfs-daemons/noble,now 1.54.0-1ubuntu2 amd64 [installed,automatic]
gvfs-daemons/noble 1.54.0-1ubuntu2 i386
gvfs-fuse/noble,now 1.54.0-1ubuntu2 amd64 [installed,automatic]
gvfs-fuse/noble 1.54.0-1ubuntu2 i386
gvfs-libs/noble,now 1.54.0-1ubuntu2 amd64 [installed,automatic]
gvfs-libs/noble 1.54.0-1ubuntu2 i386
gvfs/noble,now 1.54.0-1ubuntu2 amd64 [installed,automatic]
gvfs/noble 1.54.0-1ubuntu2 i386

### Describe the bug

When looking for the same issue online its appreciated to include the missing lib in the AppImage instead of relying on the system to provide it. Seems like a Version issue again, as the lib is available on my system

### To reproduce

call $ ./authme-5.3.1-linux-x64.appimage
Receive prompt:
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so

**Comment by Levminer** [comment]
Dependencies are handled by Tauri: [tauri.app/start/prerequisites](https://tauri.app/start/prerequisites/)

Should be fixed on the next version.
